### ISSUE TITLE
Escape apostrophes if present

### ISSUE THREAD

**Issue by wesbos** [BriteSnow/vscode-toggle-quotes#3]
The Sublime version of this plugin would escape any apostrophes:

`"Hello I'm Hungry"`

would change to 

`'Hello I\'m Hungry'`

Possible with this one as well?

**Comment by jeremychone** [comment]
@wesbos I get your point, however, I am not sure if this will conflict or not with #4. Also, one of my current design goals is to have this plugin not destructive, meaning, if you can always go back to the original stage by cycling through the toggle. 

Let me think about this one. I will probably do #4 first, and then see how this will behave given my design goals.

**Comment by wesbos** [comment]
thanks for the response - definitely do #4 first. In the sublime plugin it always goes back to the original as well

**Comment by jeremychone** [comment]
@wesbos Cool, I will look at the sublime text plugin (usually, they are done very smart). Can you point me the name so that I do not look at the wrong one.

**Comment by dorian-marchal** [comment]
For reference, [this atom package](https://github.com/atom/toggle-quotes) also escapes existing quotes.

**Comment by evaera** [comment]
Would like to see this. Slight gotcha I ran into:

I want to convert a double quote string to a template literal, but with the cursor (`][`) in this position, it just does nothing. It does something if the cursor is on the right side of the apostrophe, but then it picks up the apostrophe as the left-bound and the double-quote as the right-bound of the string literal.

```ts
"This stri][ng won't work because of the apostrophe."
````

Would be great if:
- The extension enforced matching pairs of quote types when detecting the string literal, since a string must begin and end with the same character (single quote, double quote, or back tick)
- If the auto escaping doesn't work out, it would make sense to then scan the string literal and if it contains a string bounding character (single quote, double quote, or back tick) to skip converting to that type. (in the case that I have above, it'd just swap directly from double-quote to back-tick)

**Comment by jeremychone** [comment]
@evaera Correct, this is a different issue as the one listed here, and in a way less disruptive than this ticket. here is the ticket for your issue #8.

**Comment by ndbroadbent** [comment]
@jeremychone I think this is the Sublime plugin that @wesbos was referring to: https://github.com/colinta/SublimeChangeQuotes
(I think also used this plugin in the past.)

> Also, one of my current design goals is to have this plugin not destructive, meaning, if you can always go back to the original stage by cycling through the toggle.

Yes this is possible by escaping / unescaping any inner quotes. The full cycle in JS should be like this:

* "Hello I'm Hungry"
* 'Hello I\'m Hungry'
* `Hello I'm hungry`
* "Hello I'm hungry"

More examples:

* '\'Quotes\' "inside" `string`'
* `'Quotes' "inside" \`string\``
* "'Quotes' \"inside\" `string`"
* '\'Quotes\' "inside" `string`'

I think shouldn't be too hard to do for a strings on a single line

**Comment by jeremychone** [comment]
@ndbroadbent thanks for the examples. Let me think about it. Might add another command "toggle with escape", which user can bind to the key. But fist, the plugin needs to be smarter on finding the right pair.

**Comment by jeremychone** [comment]
After reflection, for now, at least, escaping and unescaping chars are out of scope. This will open is medium size pandora box and probably would distract with things more in line with the plugin philosophy.
